name: Run Shell Scripts

on: push

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Make scripts executable
      run: |
        chmod +x main.sh
        chmod +x test_main.sh

    - name: Run main.sh
      run: bash main.sh

    - name: Run test_main.sh
      run: bash test_main.sh
